# SEE: https://docs.github.com/en/actions/learn-github-actions/variables#default-environment-variables
# SEE: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-net
name: Airports
run-name: Airports ${{ github.ref_name }}
on: workflow_dispatch
env:
    buildConfiguration: 'Release'
    artifactName: 'archive'
jobs:
    build:
        runs-on: ubuntu-latest
        steps:
        - uses: actions/checkout@v4
          with:
            ref: main
            path: ./target
        - uses: actions/checkout@v4
          with:
            repository: gbosystems/synthetic-api-scripts
            ref: main
            path: ./scripts
        - uses: actions/checkout@v4
          with:
            repository: davidmegginson/ourairports-data
            ref: main
            path: ./data/airports
        - uses: actions/setup-node@v4
          with:
            node-version: 20
            cache: npm
            cache-dependency-path: ./scripts
        - name: Process airports
          shell: bash
          run: |
            rm -r -f "${{ github.workspace }}/target/airports/"
            npm install "${{ github.workspace }}/scripts/"
            node "${{ github.workspace }}/scripts/process-airports.mjs" --source "${{ github.workspace }}/data/airports" --destination "${{ github.workspace }}/target/airports"
        - name: Commit changes
          shell: bash
          run: |
            cd ./target
            date=$(date +%F)
            git config user.name github-actions
            git config user.email github-actions@github.com
            git add .
            git commit -m "Automated download on $date"
            git push