# SEE: https://docs.github.com/en/actions/learn-github-actions/variables#default-environment-variables
# SEE: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-net
name: Hospitals
run-name: Hospitals ${{ github.ref_name }}
on:
    workflow_dispatch:
    schedule:
      - cron: "20 3 * * *"
env:
    buildConfiguration: 'Release'
    artifactName: 'archive'
jobs:
    build:
        runs-on: ubuntu-latest
        steps:
        - uses: actions/checkout@v4
          with:
            ref: main
            path: ./target
        - uses: actions/checkout@v4
          with:
            repository: gbosystems/data-scripts
            ref: main
            path: ./scripts
        - uses: actions/setup-node@v4
          with:
            node-version: 20
            cache: npm
            cache-dependency-path: ./scripts
        - name: Download hospitals
          shell: bash
          run: |
            cp -r "${{ github.workspace }}/target/hospitals" "${{ runner.temp }}/hospitals"
            rm -r -f "${{ github.workspace }}/target/hospitals/"
            ls -la "${{ runner.temp }}"
            exit 1
            node "${{ github.workspace }}/scripts/download-hospitals.mjs" --path "${{ github.workspace }}/target/hospitals" --existing "${{ runner.temp }}/hospitals" --hereApiKey "${{ secrets.HERE_API_KEY }}"
        - name: Commit changes
          shell: bash
          run: |
            cd ./target
            date=$(date +%F)
            git config user.name github-actions
            git config user.email github-actions@github.com
            git add .
            git commit -m "Automated download on $date"
            git push