# SEE: https://docs.github.com/en/actions/learn-github-actions/variables#default-environment-variables
# SEE: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-net
name: Ports
run-name: Ports ${{ github.ref_name }}
on:
    workflow_dispatch:
    schedule:
      - cron: "10 3 * * *"
env:
    buildConfiguration: 'Release'
    artifactName: 'archive'
jobs:
    build:
        runs-on: ubuntu-latest
        steps:
        - uses: actions/checkout@v4
          with:
            ref: main
            path: ./target
        - uses: actions/checkout@v4
          with:
            repository: gbosystems/data-scripts
            ref: main
            path: ./scripts
        - uses: actions/setup-node@v4
          with:
            node-version: 20
        - name: Download ports
          shell: bash
          run: |
            rm -r -f "${{ github.workspace }}/target/ports/"
            node "${{ github.workspace }}/scripts/download-ports.mjs" --path "${{ github.workspace }}/target/ports"
          env:
            NODE_EXTRA_CA_CERTS: ${{ github.workspace }}/scripts/nga.mil-trust-chain.pem
        - name: Commit changes
          shell: bash
          run: |
            cd ./target
            date=$(date +%F)
            git config user.name github-actions
            git config user.email github-actions@github.com
            git add .
            git commit -m "Automated download on $date"
            git push